<?php

namespace EShopBundle\Repository;

/**
 * OderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OderRepository extends \Doctrine\ORM\EntityRepository
{
}
