<?php

namespace EShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderProductRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OrderProductRepository extends EntityRepository
{
}
